# Generated by Django 5.1.2 on 2024-10-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='AuthorUser',
            new_name='author_user',
        ),
    ]
