# Generated by Django 5.1.2 on 2024-10-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_authoruser_author_author_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
